from datetime import datetime, timezone
from typing import Dict, List

import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

from ..core.config import DATABASE_URL

engine: Engine = create_engine(
    DATABASE_URL,
    future=True,
    pool_pre_ping=True,
    connect_args={"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {},
)

CREATE_TABLES_SQL = [
    """CREATE TABLE IF NOT EXISTS history(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        message TEXT,
        source TEXT,
        prediction TEXT,
        confidence REAL,
        timestamp TEXT
    )""",
    """CREATE TABLE IF NOT EXISTS users(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        created_at TEXT NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS user_history(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER NOT NULL,
        message TEXT NOT NULL,
        source TEXT NOT NULL,
        prediction TEXT NOT NULL,
        confidence REAL NOT NULL,
        timestamp TEXT NOT NULL,
        FOREIGN KEY(user_id) REFERENCES users(id)
    )""",
]

# PostgreSQL-compatible schema. SQLite uses a separate schema because its
# autoincrement syntax differs from PostgreSQL SERIAL/IDENTITY.
POSTGRES_TABLES_SQL = [
    """CREATE TABLE IF NOT EXISTS history(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        message TEXT,
        source TEXT,
        prediction TEXT,
        confidence DOUBLE PRECISION,
        timestamp TEXT
    )""",
    """CREATE TABLE IF NOT EXISTS users(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        created_at TEXT NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS user_history(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id),
        message TEXT NOT NULL,
        source TEXT NOT NULL,
        prediction TEXT NOT NULL,
        confidence DOUBLE PRECISION NOT NULL,
        timestamp TEXT NOT NULL
    )""",
]


def create_database() -> None:
    statements = POSTGRES_TABLES_SQL if DATABASE_URL.startswith("postgres") else CREATE_TABLES_SQL
    with engine.begin() as connection:
        for statement in statements:
            connection.execute(text(statement))


def database_health() -> bool:
    try:
        with engine.connect() as connection:
            connection.execute(text("SELECT 1"))
        return True
    except Exception:
        return False


def now_text() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def save_history(message: str, source: str, prediction: str, confidence: float) -> int:
    with engine.begin() as connection:
        if DATABASE_URL.startswith("postgres"):
            result = connection.execute(
                text("INSERT INTO history(message, source, prediction, confidence, timestamp) VALUES (:message,:source,:prediction,:confidence,:timestamp) RETURNING id"),
                {"message": message, "source": source, "prediction": prediction, "confidence": confidence, "timestamp": now_text()},
            )
            return int(result.scalar_one())
        result = connection.execute(
            text("INSERT INTO history(message, source, prediction, confidence, timestamp) VALUES (:message,:source,:prediction,:confidence,:timestamp)"),
            {"message": message, "source": source, "prediction": prediction, "confidence": confidence, "timestamp": now_text()},
        )
        return int(result.lastrowid)


def get_history(limit: int | None = None) -> List[Dict]:
    query = "SELECT id, message, source, prediction, confidence, timestamp FROM history ORDER BY id DESC"
    params = {}
    if limit is not None:
        query += " LIMIT :limit"
        params["limit"] = limit
    with engine.connect() as connection:
        rows = connection.execute(text(query), params).mappings().all()
        return [dict(row) for row in rows]


def get_history_dataframe() -> pd.DataFrame:
    with engine.connect() as connection:
        return pd.read_sql(text("SELECT * FROM history"), connection)


def create_user(name: str, email: str, password_hash: str) -> Dict:
    with engine.begin() as connection:
        if DATABASE_URL.startswith("postgres"):
            result = connection.execute(
                text("INSERT INTO users(name,email,password_hash,created_at) VALUES (:name,:email,:password_hash,:created_at) RETURNING id"),
                {"name": name, "email": email.lower(), "password_hash": password_hash, "created_at": now_text()},
            )
            user_id = int(result.scalar_one())
        else:
            result = connection.execute(
                text("INSERT INTO users(name,email,password_hash,created_at) VALUES (:name,:email,:password_hash,:created_at)"),
                {"name": name, "email": email.lower(), "password_hash": password_hash, "created_at": now_text()},
            )
            user_id = int(result.lastrowid)
    return get_user_by_id(user_id)


def get_user_by_email(email: str):
    with engine.connect() as connection:
        row = connection.execute(text("SELECT id,name,email,password_hash,created_at FROM users WHERE email=:email"), {"email": email.lower()}).mappings().first()
        return dict(row) if row else None


def get_user_by_id(user_id: int):
    with engine.connect() as connection:
        row = connection.execute(text("SELECT id,name,email,password_hash,created_at FROM users WHERE id=:id"), {"id": user_id}).mappings().first()
        return dict(row) if row else None


def save_user_history(user_id: int, message: str, source: str, prediction: str, confidence: float) -> int:
    with engine.begin() as connection:
        if DATABASE_URL.startswith("postgres"):
            result = connection.execute(
                text("INSERT INTO user_history(user_id,message,source,prediction,confidence,timestamp) VALUES (:user_id,:message,:source,:prediction,:confidence,:timestamp) RETURNING id"),
                {"user_id": user_id, "message": message, "source": source, "prediction": prediction, "confidence": confidence, "timestamp": now_text()},
            )
            return int(result.scalar_one())
        result = connection.execute(
            text("INSERT INTO user_history(user_id,message,source,prediction,confidence,timestamp) VALUES (:user_id,:message,:source,:prediction,:confidence,:timestamp)"),
            {"user_id": user_id, "message": message, "source": source, "prediction": prediction, "confidence": confidence, "timestamp": now_text()},
        )
        return int(result.lastrowid)


def get_user_history(user_id: int, limit: int = 100) -> List[Dict]:
    with engine.connect() as connection:
        rows = connection.execute(
            text("SELECT id,message,source,prediction,confidence,timestamp FROM user_history WHERE user_id=:user_id ORDER BY id DESC LIMIT :limit"),
            {"user_id": user_id, "limit": limit},
        ).mappings().all()
        return [dict(row) for row in rows]


def get_user_dashboard(user_id: int) -> Dict:
    with engine.connect() as connection:
        row = connection.execute(
            text("SELECT COUNT(*) AS total, COALESCE(SUM(CASE WHEN prediction <> 'SAFE' THEN 1 ELSE 0 END),0) AS threats FROM user_history WHERE user_id=:user_id"),
            {"user_id": user_id},
        ).mappings().one()
    total = int(row["total"])
    threats = int(row["threats"])
    safe = total - threats
    return {"total_scans": total, "threats_found": threats, "safe_scans": safe, "scam_scans": threats, "distribution": {"SAFE": safe, "SCAM / PHISHING": threats}}
